### ISSUE TITLE
Remove hard coded paths

### ISSUE THREAD

**Issue by pazzarpj** [pazzarpj/Fixate#2]
There are some hard coded paths that were missed in the initial port. Remove traces of these and add the functionality into a configuration file.

**Comment by kmolnar** [comment]
I've extracted the base_csv_path from __main__.py, couldn't find any more hard-coded paths.
If there are more, let me know where they are, and I'll pull them out.

**Comment by kmolnar** [comment]
Resolved in version 0.3.2
